### ISSUE TITLE
Getting Started activity is empty

### ISSUE THREAD

**Issue by Akshshr** [shchurov/ParticleView#2]
Hey just wanted to point out that the getting started activity just contains the android launcher icon. No motion no particles

**Comment by mikehodz** [comment]
Hi @Akshshr!
That's intentional. Just to give an idea about the minimal amount of code you need to write to display a single static particle.
It has [empty `update()` method](https://github.com/shchurov/ParticleView/blob/master/sample/src/main/java/com/github/shchurov/particleview/sample/getting_started/GettingStartedActivity.java#L48), which means that the state is not being changed with time.
Check other samples if you're looking for something more complex.

**Comment by Akshshr** [comment]
Ah got it! Thanks for the quick reply! That clears it out :)
